### ISSUE TITLE
download file sizes are 0 bytes

### ISSUE THREAD

**Issue by sivaanna** [gingerlime/smugline#13]
Thanks for the script. I tried to use the script.

Listing the album works fine, but when i tried to download albums with image and videos, it shows the message as downloading but all the files are 0 byte size.

any help?

Thanks in advance.

**Comment by gingerlime** [comment]
Could it be that the album is private? It might not work on private albums, but it should do on unlisted ones. Otherwise, please provide more details about the OS you're running, any output logs or anything else that might help to trace this problem.

**Comment by sivaanna** [comment]
thanks for the quick response.

yes, it is a private album, but i thought with providing the credentials, we should be able to download the private albums.

i changed the setting to unlisted and i am able to download images now - thanks.

but i still see problem with videos - it downloads them with just the initial frame - not the full video - quick time reports as corrupted file.

any idea?

Thanks
Siva

**Comment by gingerlime** [comment]
are you using `--media=all` ?

**Comment by sivaanna** [comment]
yes

**Comment by sivaanna** [comment]
sorry, do you know if this is a problem with the script or something else?

**Comment by gingerlime** [comment]
There seem to be a problem, but I think it's related to SmugMug. When I look at a video in an album, and click the info option - it shows a file size of only a few Kb - whereas when I click download, it will download a few Mb ... So somehow SmugMug must store a thumbnail or the video and the video separately. And looks like smugline can only find the thumbnail version.

Please see #6 - the download functionality is kinda undocumented, so SmugMug can change things and it will stop working. Maybe this is better with the v2.0 API, but I haven't had a chance to look into this yet.

I'll try to see if I can figure something out, but can't promise anything unfortunately.
