### ISSUE TITLE
cannot upload photos

### ISSUE THREAD

**Issue by afruscione** [gingerlime/smugline#25]
Hello,
I installed the script which seems to behave as expected when I try to list the albums in my account and also when I tried to create a new album, so I know that the API key works. 
However  I do not seem to be able to upload photos. The script simply exists silently.
Any suggestions?

**Comment by gingerlime** [comment]
Hello @afruscione. I'm not sure what might be the problem. A few questions/suggestions:

1. Are you sure that the folder you're uploading from has any images? (or please use `--from=/path/to/images`)
2. Can you post the command you're running and any output you get? (remove any sensitive API keys or passwords please before posting). Ideally for the album listing as well as the upload commands.

**Comment by afruscione** [comment]
Sorry, my fault. 
out of habit I was using 
--from=~/Downloads/test 
but as soon as I wrote the explicit path 
--from=/Users/antonella/Downloads/test
all worked
Your script is great! Thank you very much

**Comment by gingerlime** [comment]
Glad to hear, @afruscione !

There might be a simple way to parse the path correctly (and translate `~/Downloads` to `/Users/xyz/Downloads`). So you might have stumbled over a small bug. I'll look into it.
